[features]
  resolution = true
  skip-lint = false

[programs.localnet]
  sablier_lockup = "5rRqnrYc5v1HTWub3nViVX1LwrrRrQTshvGiAAJvK3Er"
  sablier_merkle_instant = "7gHPcvMam4Fs6eLV792xJui8bfXZwruq7RZCknrwECP1"

[provider]
  cluster = "localnet"
  wallet = "~/.config/solana/id.json"

[registry]
  url = "https://api.apr.dev"

[toolchain]
  anchor_version = "0.31.1"
  solana_version = "2.1.21"
