[features]
  resolution = true
  skip-lint = false

[programs.localnet]
  sablier_lockup = "4EauRKrNErKfsR4XetEZJNmvACGHbHnHV4R5dvJuqupC"
  sablier_merkle_instant = "7XrxoQejBoGouW4V3aozTSwub7xSDjYqB4Go7YLjF9rV"

[provider]
  cluster = "localnet"
  wallet = "~/.config/solana/id.json"

[registry]
  url = "https://api.apr.dev"

[toolchain]
  anchor_version = "0.31.1"
  solana_version = "2.2.12"
