[features]
  resolution = true
  skip-lint = false

[programs.localnet]
  sablier_lockup = "Hs1cF7Xr8XZMsKJCgZt2npNBr83iBqrNiAfZoeVYXA2F"
  sablier_merkle_instant = "AnUDJ4SX9YRc6mMjm7yf8ZLd1x2i6VFNJaXvQaGeXoZm"

[provider]
  cluster = "localnet"
  wallet = "~/.config/solana/id.json"

[registry]
  url = "https://api.apr.dev"

[toolchain]
  anchor_version = "0.31.1"
  solana_version = "2.1.21"
