name: "CI"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - "staging"

jobs:
  ci:
    runs-on: "macos-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Set up Sablier devkit and install Node.js dependencies"
        uses: "sablier-labs/devkit/actions/setup@main"
        with:
          package-manager: "bun"

      - name: "Set up Rust, Solana, and Anchor"
        uses: "sablier-labs/gha-utils/.github/actions/anchor-toolchain@main"
        with:
          anchor-version: "0.31.1"
          rust-version: "nightly"
          solana-version: "2.1.21"

      - name: "Install Trident"
        run: "cargo install trident-cli"

      - name: "Cache Anchor build artifacts"
        id: "cache-build"
        uses: "sablier-labs/gha-utils/.github/actions/solana-cache@main"
        with:
          cache-path: target

      - name: "Build the programs"
        if: steps.cache-build.outputs.cache-status != 'primary'
        run: "just build"

      - name: "Run the Rust code checks"
        if: steps.cache-build.outputs.cache-status != 'primary'
        run: "just rust-check"

      - name: "Run the other code checks"
        run: | # shell
          just prettier-check
          just biome-check
          just tsc-check

      - name: "Run the tests"
        if: steps.cache-build.outputs.cache-status != 'primary'
        run: "just test-lite"

      - name: "Run the fuzz tests"
        if: steps.cache-build.outputs.cache-status != 'primary'
        run: "just fuzz-lockup"

      - name: "Add summary"
        run: | # shell
          echo "## CI result" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Passed" >> $GITHUB_STEP_SUMMARY
